name: Matrix Flow
on:
    push:
        branches: 
            - master
jobs:
    build:
        continue-on-error: true
        strategy:
          matrix:
            node-versions: [12,14,16]
            operating-systems: ['unbuntu-latest', 'windows-latest']
            exclude:
              - node-version: 12
                operating-system: windows-latest
              - node-version: 12
                operating-system: ubuntu-latest
              - node-version: 14
                operating-system: ubuntu-latest
              - node-version: 16
                operating-system: ubuntu-latest


        runs-on: ${{ matrix.operating-systems }}
        steps:
            - name: get Code
              uses: actions/checkout@v4
            - name: Install NodeJS
              uses: actions/setup-node@v4
              with:
                    node-version: ${{ matrix.node-versions }}
            - name: Install Dependencies
              run: npm ci
            - name: build Project
              run: npm run build  